In [1]:
import numpy as np

In [2]:
#1st array
my_array = np.array([1,2,3,4])
my_array

array([1, 2, 3, 4])

In [3]:
print(type(my_array))

<class 'numpy.ndarray'>


In [4]:
my_array.dtype

dtype('int32')

In [5]:
#2d array
My2nd = np.array([[1,2,3],[5,6,7]])
My2nd

array([[1, 2, 3],
       [5, 6, 7]])

In [6]:
#3d array
My3d = np.array([[[1,2,3,4],[5,6,7,8]],[[8,9,10,12],[14,16,17,19]]])
My3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 8,  9, 10, 12],
        [14, 16, 17, 19]]])

In [7]:
My2 = np.array([[1,2,3],[5,6,7]],dtype=float)
My2

array([[1., 2., 3.],
       [5., 6., 7.]])

In [8]:
#Dimensin
print(my_array.ndim)
print(My2nd.ndim)
print(My3d.ndim)

1
2
3


In [9]:
#Shape
print(my_array.shape)
print(My2nd.shape)
print(My3d.shape)

(4,)
(2, 3)
(2, 2, 4)


In [10]:
#Size
print(my_array.size)
print(My2nd.size)
print(My3d.size)

4
6
16


In [11]:
#datatype
print(my_array.dtype)
print(My2nd.dtype)
print(My2.dtype)

int32
int32
float64


In [12]:
#itemsize
print(my_array.itemsize)
print(My2nd.itemsize)
print(My3d.itemsize)

4
4
4


In [13]:
#memory location
print(my_array.data)
print(My2nd.data)
print(My3d.data)

In [14]:
#Index and Slicing
#Index
print(my_array)
print(my_array[2])
print(My2nd)
print(My2nd[1,2])
print(My3d)
print(My3d[1,0,2])

[1 2 3 4]
3
[[1 2 3]
 [5 6 7]]
7
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 8  9 10 12]
  [14 16 17 19]]]
10


In [15]:
#Bool index
print(my_array)
bool_value = [True,False,True,True]
print(my_array[bool_value])

[1 2 3 4]
[1 3 4]


In [16]:
#Slicing
#1D
print(my_array[1:3])
print(my_array[::-1])
print(my_array[::2])
print()
#2D
New2d = np.array([[1,2,3,4],[6,7,8,9],[3,8,9,10],[2,3,4,5]])
print(New2d)
print(New2d[1:3,1:3])
print(New2d[:2])
print(New2d[:,1:])
print(New2d[:,:-1])

[2 3]
[4 3 2 1]
[1 3]

[[ 1  2  3  4]
 [ 6  7  8  9]
 [ 3  8  9 10]
 [ 2  3  4  5]]
[[7 8]
 [8 9]]
[[1 2 3 4]
 [6 7 8 9]]
[[ 2  3  4]
 [ 7  8  9]
 [ 8  9 10]
 [ 3  4  5]]
[[1 2 3]
 [6 7 8]
 [3 8 9]
 [2 3 4]]


In [17]:
#3D
print(My3d)
print(My3d[0,1,1:3])
print(My3d[...,:])
print(My3d[:,0,...])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 8  9 10 12]
  [14 16 17 19]]]
[6 7]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 8  9 10 12]
  [14 16 17 19]]]
[[ 1  2  3  4]
 [ 8  9 10 12]]


In [18]:
#Operations:
First = np.array([1,2,3,4])
Sec = np.array([5,6,7,8])
print(First)
print(Sec)

[1 2 3 4]
[5 6 7 8]


In [19]:
D = First+Sec
print(D)
E = First-Sec
print(E)
F = First*Sec
print(F)
G = First/Sec
print(G)
H = First//Sec
print(H)
I = First%Sec
print(I)
L = First**Sec
print(L)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0 0 0 0]
[1 2 3 4]
[    1    64  2187 65536]


In [20]:
#Transpose
print(New2d)
print(New2d.T)
print(np.sort(New2d))
print(np.sort(New2d,axis=0))
print(np.sort(New2d,axis=1))
print(np.sort(New2d,axis=-1))

[[ 1  2  3  4]
 [ 6  7  8  9]
 [ 3  8  9 10]
 [ 2  3  4  5]]
[[ 1  6  3  2]
 [ 2  7  8  3]
 [ 3  8  9  4]
 [ 4  9 10  5]]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [ 3  8  9 10]
 [ 2  3  4  5]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  7  8  9]
 [ 6  8  9 10]]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [ 3  8  9 10]
 [ 2  3  4  5]]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [ 3  8  9 10]
 [ 2  3  4  5]]


In [21]:
#conact
result = np.concatenate((First,Sec))
print(result)

[1 2 3 4 5 6 7 8]


In [22]:
fi2nd = np.array([[1,2,3],[4,5,6]])
sec2nd = np.array([[4,5,6],[7,8,9]])
print(np.concatenate((fi2nd,sec2nd),axis=0))
print(np.concatenate((fi2nd,sec2nd),axis=1))

[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [23]:
print(np.split(My3d,2,axis=0))
print(np.split(My3d,2,axis=1))

[array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]]), array([[[ 8,  9, 10, 12],
        [14, 16, 17, 19]]])]
[array([[[ 1,  2,  3,  4]],

       [[ 8,  9, 10, 12]]]), array([[[ 5,  6,  7,  8]],

       [[14, 16, 17, 19]]])]


In [24]:
#Stat operations
print(New2d)
print(np.mean(New2d,axis=0))
print(np.mean(New2d,axis=1))
print(np.median(New2d,axis=0))
print(np.median(New2d,axis=1))
print(np.std(New2d,axis=0))
print(np.std(New2d,axis=1))
print(np.sum(New2d,axis=0))
print(np.sum(New2d,axis=1))
print(np.max(New2d,axis=0))
print(np.max(New2d,axis=1))
print(np.min(New2d,axis=0))
print(np.min(New2d,axis=1))

[[ 1  2  3  4]
 [ 6  7  8  9]
 [ 3  8  9 10]
 [ 2  3  4  5]]
[3. 5. 6. 7.]
[2.5 7.5 7.5 3.5]
[2.5 5.  6.  7. ]
[2.5 7.5 8.5 3.5]
[1.87082869 2.54950976 2.54950976 2.54950976]
[1.11803399 1.11803399 2.6925824  1.11803399]
[12 20 24 28]
[10 30 30 14]
[ 6  8  9 10]
[ 4  9 10  5]
[1 2 3 4]
[1 6 3 2]


In [25]:
#Types of Metrix
print(np.zeros(5))
print(np.zeros((3,4)))
print(np.zeros((3,4,2)))
print(np.ones(5))
print(np.ones((3,4)))
print(np.ones((3,4,2)))
print(np.full((3,4),-1))
print(np.eye(3))
print(np.eye(4,k=2))

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
print(np.arange(10))
print(np.arange(3,13))
print(np.arange(0,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 3  4  5  6  7  8  9 10 11 12]
[ 0  2  4  6  8 10]


In [27]:
print(np.random.random(5))
print(np.random.random((2,3)))

[0.32110485 0.6501734  0.16408463 0.31003606 0.59464633]
[[0.00228152 0.96324679 0.82818999]
 [0.48020141 0.56113099 0.37837612]]
